export const browserCoreExamples = [
  "azmeth browser status",
  "azmeth browser start",
  "azmeth browser stop",
  "azmeth browser tabs",
  "azmeth browser open https://example.com",
  "azmeth browser focus abcd1234",
  "azmeth browser close abcd1234",
  "azmeth browser screenshot",
  "azmeth browser screenshot --full-page",
  "azmeth browser screenshot --ref 12",
  "azmeth browser snapshot",
  "azmeth browser snapshot --format aria --limit 200",
  "azmeth browser snapshot --efficient",
  "azmeth browser snapshot --labels",
];

export const browserActionExamples = [
  "azmeth browser navigate https://example.com",
  "azmeth browser resize 1280 720",
  "azmeth browser click 12 --double",
  'azmeth browser type 23 "hello" --submit',
  "azmeth browser press Enter",
  "azmeth browser hover 44",
  "azmeth browser drag 10 11",
  "azmeth browser select 9 OptionA OptionB",
  "azmeth browser upload /tmp/file.pdf",
  'azmeth browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "azmeth browser dialog --accept",
  'azmeth browser wait --text "Done"',
  "azmeth browser evaluate --fn '(el) => el.textContent' --ref 7",
  "azmeth browser console --level error",
  "azmeth browser pdf",
];
